// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.

package core

import (
	"fmt"
	"strconv"
)

func (x DayOfWeek) Format() string {
	value := int32(x)
	if name, ok := DayOfWeek_name[value]; ok {
		return name
	}
	return strconv.Itoa(int(value))
}

func (x DayOfWeek) ToString() string {
	return x.Format()
}

func (x *DayOfWeek) Parse(value string) error {
	if x == nil || value == "" {
		return nil
	}
	if enumValue, ok := DayOfWeek_value[value]; ok {
		*x = DayOfWeek(enumValue)
		return nil
	}
	parsed, err := strconv.ParseInt(value, 10, 32)
	if err != nil {
		return fmt.Errorf("invalid DayOfWeek: %s", value)
	}
	if _, ok := DayOfWeek_name[int32(parsed)]; !ok {
		return fmt.Errorf("invalid DayOfWeek: %s", value)
	}
	*x = DayOfWeek(parsed)
	return nil
}

func ParseDayOfWeek(value string) (DayOfWeek, error) {
	var enumValue DayOfWeek
	if err := (&enumValue).Parse(value); err != nil {
		return enumValue, err
	}
	return enumValue, nil
}
