// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.

package core

import (
	"fmt"
	"strconv"
)

func (x File_Mode) Format() string {
	value := int32(x)
	if name, ok := File_Mode_name[value]; ok {
		return name
	}
	return strconv.Itoa(int(value))
}

func (x File_Mode) ToString() string {
	return x.Format()
}

func (x *File_Mode) Parse(value string) error {
	if x == nil || value == "" {
		return nil
	}
	if enumValue, ok := File_Mode_value[value]; ok {
		*x = File_Mode(enumValue)
		return nil
	}
	parsed, err := strconv.ParseInt(value, 10, 32)
	if err != nil {
		return fmt.Errorf("invalid File_Mode: %s", value)
	}
	if _, ok := File_Mode_name[int32(parsed)]; !ok {
		return fmt.Errorf("invalid File_Mode: %s", value)
	}
	*x = File_Mode(parsed)
	return nil
}

func ParseFile_Mode(value string) (File_Mode, error) {
	var enumValue File_Mode
	if err := (&enumValue).Parse(value); err != nil {
		return enumValue, err
	}
	return enumValue, nil
}
