// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: fino/core/file.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode distinguishes directories from regular files.
type File_Mode int32

const (
	File_MODE_UNSPECIFIED File_Mode = 0
	File_MODE_DIR         File_Mode = 1
	File_MODE_FILE        File_Mode = 2
)

// Enum value maps for File_Mode.
var (
	File_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_DIR",
		2: "MODE_FILE",
	}
	File_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_DIR":         1,
		"MODE_FILE":        2,
	}
)

func (x File_Mode) Enum() *File_Mode {
	p := new(File_Mode)
	*p = x
	return p
}

func (x File_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (File_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_fino_core_file_proto_enumTypes[0].Descriptor()
}

func (File_Mode) Type() protoreflect.EnumType {
	return &file_fino_core_file_proto_enumTypes[0]
}

func (x File_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use File_Mode.Descriptor instead.
func (File_Mode) EnumDescriptor() ([]byte, []int) {
	return file_fino_core_file_proto_rawDescGZIP(), []int{0, 0}
}

// File represents a named filesystem entry; mode is the sole entry type.
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Entry name relative to its parent.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Entry type; zero means the type is unknown.
	Mode File_Mode `protobuf:"varint,5,opt,name=mode,proto3,enum=fino.core.File_Mode" json:"mode,omitempty"`
	// Optional metadata for the entry.
	Info *File_Info `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	// Directory children; must be empty for regular files.
	Files []*File `protobuf:"bytes,10,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fino_core_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_fino_core_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_fino_core_file_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetMode() File_Mode {
	if x != nil {
		return x.Mode
	}
	return File_MODE_UNSPECIFIED
}

func (x *File) GetInfo() *File_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *File) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

// Info contains entry metadata; the entry name belongs to File.name.
type File_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filename suffix without the leading dot; empty when there is no suffix.
	Suffix string `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	// Size in bytes; must be non-negative.
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Last metadata change time, not creation time; absent when unavailable.
	ChangeTime *Timestamp `protobuf:"bytes,10,opt,name=change_time,json=changeTime,proto3" json:"changeTime,omitempty"`
	// Last content modification time; absent when unavailable.
	ModifyTime *Timestamp `protobuf:"bytes,11,opt,name=modify_time,json=modifyTime,proto3" json:"modifyTime,omitempty"`
}

func (x *File_Info) Reset() {
	*x = File_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fino_core_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File_Info) ProtoMessage() {}

func (x *File_Info) ProtoReflect() protoreflect.Message {
	mi := &file_fino_core_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File_Info.ProtoReflect.Descriptor instead.
func (*File_Info) Descriptor() ([]byte, []int) {
	return file_fino_core_file_proto_rawDescGZIP(), []int{0, 0}
}

func (x *File_Info) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *File_Info) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File_Info) GetChangeTime() *Timestamp {
	if x != nil {
		return x.ChangeTime
	}
	return nil
}

func (x *File_Info) GetModifyTime() *Timestamp {
	if x != nil {
		return x.ModifyTime
	}
	return nil
}

var File_fino_core_file_proto protoreflect.FileDescriptor

var file_fino_core_file_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x1a, 0x14, 0x66, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x03, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x66, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66,
	0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x6e, 0x6f, 0x2e, 0x63,
	0x6f, 0x72, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a,
	0xac, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x66, 0x66,
	0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x69, 0x6e, 0x6f,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x66, 0x69, 0x6e, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39,
	0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x49, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f,
	0x44, 0x45, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x52,
	0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6e, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x66, 0x69, 0x6e, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x3b,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fino_core_file_proto_rawDescOnce sync.Once
	file_fino_core_file_proto_rawDescData = file_fino_core_file_proto_rawDesc
)

func file_fino_core_file_proto_rawDescGZIP() []byte {
	file_fino_core_file_proto_rawDescOnce.Do(func() {
		file_fino_core_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_fino_core_file_proto_rawDescData)
	})
	return file_fino_core_file_proto_rawDescData
}

var file_fino_core_file_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fino_core_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fino_core_file_proto_goTypes = []interface{}{
	(File_Mode)(0),    // 0: fino.core.File.Mode
	(*File)(nil),      // 1: fino.core.File
	(*File_Info)(nil), // 2: fino.core.File.Info
	(*Timestamp)(nil), // 3: fino.core.Timestamp
}
var file_fino_core_file_proto_depIdxs = []int32{
	0, // 0: fino.core.File.mode:type_name -> fino.core.File.Mode
	2, // 1: fino.core.File.info:type_name -> fino.core.File.Info
	1, // 2: fino.core.File.files:type_name -> fino.core.File
	3, // 3: fino.core.File.Info.change_time:type_name -> fino.core.Timestamp
	3, // 4: fino.core.File.Info.modify_time:type_name -> fino.core.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fino_core_file_proto_init() }
func file_fino_core_file_proto_init() {
	if File_fino_core_file_proto != nil {
		return
	}
	file_fino_core_time_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fino_core_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fino_core_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fino_core_file_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fino_core_file_proto_goTypes,
		DependencyIndexes: file_fino_core_file_proto_depIdxs,
		EnumInfos:         file_fino_core_file_proto_enumTypes,
		MessageInfos:      file_fino_core_file_proto_msgTypes,
	}.Build()
	File_fino_core_file_proto = out.File
	file_fino_core_file_proto_rawDesc = nil
	file_fino_core_file_proto_goTypes = nil
	file_fino_core_file_proto_depIdxs = nil
}
