// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.

package core

import (
	"fmt"
	"strconv"
)

func (x Month) Format() string {
	value := int32(x)
	if name, ok := Month_name[value]; ok {
		return name
	}
	return strconv.Itoa(int(value))
}

func (x Month) ToString() string {
	return x.Format()
}

func (x *Month) Parse(value string) error {
	if x == nil || value == "" {
		return nil
	}
	if enumValue, ok := Month_value[value]; ok {
		*x = Month(enumValue)
		return nil
	}
	parsed, err := strconv.ParseInt(value, 10, 32)
	if err != nil {
		return fmt.Errorf("invalid Month: %s", value)
	}
	if _, ok := Month_name[int32(parsed)]; !ok {
		return fmt.Errorf("invalid Month: %s", value)
	}
	*x = Month(parsed)
	return nil
}

func ParseMonth(value string) (Month, error) {
	var enumValue Month
	if err := (&enumValue).Parse(value); err != nil {
		return enumValue, err
	}
	return enumValue, nil
}
