// Code generated by fino. DO NOT EDIT.
// Rerunning fino will overwrite this file.

package core

import (
	"fmt"
	"strconv"
)

func (x ValueKind) Format() string {
	value := int32(x)
	if name, ok := ValueKind_name[value]; ok {
		return name
	}
	return strconv.Itoa(int(value))
}

func (x ValueKind) ToString() string {
	return x.Format()
}

func (x *ValueKind) Parse(value string) error {
	if x == nil || value == "" {
		return nil
	}
	if enumValue, ok := ValueKind_value[value]; ok {
		*x = ValueKind(enumValue)
		return nil
	}
	parsed, err := strconv.ParseInt(value, 10, 32)
	if err != nil {
		return fmt.Errorf("invalid ValueKind: %s", value)
	}
	if _, ok := ValueKind_name[int32(parsed)]; !ok {
		return fmt.Errorf("invalid ValueKind: %s", value)
	}
	*x = ValueKind(parsed)
	return nil
}

func ParseValueKind(value string) (ValueKind, error) {
	var enumValue ValueKind
	if err := (&enumValue).Parse(value); err != nil {
		return enumValue, err
	}
	return enumValue, nil
}
